version: '3.3'
services:
  db:
    container_name: school_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'school'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - school-db:/var/lib/mysql
# Names our volume
volumes:
  school-db:
